### PR TITLE
Towards repo transition

### PR DESCRIPTION
**Pull request by lilnasy**
Let's at least get it to its current state. Docs, contributions ~~and CI~~ can be figured out later.

### CODE REVIEW

**Comment by lilnasy** [comment]
Includes the changes from #3. The tests are all working now. 

Ready for review.

**Comment by lilnasy** [comment]
Added CI as well, but actions are yet to be enabled on this repo. Here's one result: [lilnasy:actions:ci](https://github.com/lilnasy/deno-astro-adapter/actions/runs/6307607720/job/17124496916).

**Review by matthewp — APPROVED** [review]
Looks great! Thanks for setting up CI.

**Review by kt3k — APPROVED** [review]
LGTM. Thanks! @lilnasy

**Pull request merged**
