### PR TITLE
chore: update tests to Astro 5

### PR DESCRIPTION
**Pull request by irbull**
Updates the Deno Astro Adapter to Astro 5.0. This includes updating the dependencies in the package.json and removing the warning about `static` output mode. The `static` output mode has been removed in Astro 5.0 [1,2].

[1] https://5-0-0-beta--astro-docs-2.netlify.app/en/guides/upgrade-to/v5/#removed-hybrid-rendering-mode
[2] https://astro.build/blog/astro-5/

This change-set also update the README as we can now build with Deno 2.0 This was introduced in commit f8d18fdb40dcdd9b9e1a778c73973922d4a01b73

### CODE REVIEW

**Comment by irbull** [comment]
Don't review this yet. I've noticed a slight improvement I can make. Astro 5 has removed `hybrid` support, but this adapter still checks for it.

**Comment by irbull** [comment]
> Don't review this yet. I've noticed a slight improvement I can make. Astro 5 has removed `hybrid` support, but this adapter still checks for it.

Should be good to go now. I removed the check for the `static` output option as it's the default now that they removed `hybrid` mode. I left a few links to the docs on this.

**Comment by kt3k** [comment]
> Should be good to go now. I removed the check for the static output option as it's the default now that they removed hybrid mode. I left a few links to the docs on this.

Sounds reasonable to me as `static` mode now seems supporting optional server-side rendering https://astro.build/blog/astro-5/#simplified-prerendering

**Review by kt3k — APPROVED** [review]
LGTM

**Comment by kt3k** [comment]
Published as 0.2.0 (minor version bump because of the change of astro major version support) https://www.npmjs.com/package/@deno/astro-adapter/v/0.2.0

Thanks for your contribution!

**Pull request merged**
