### PR TITLE
Astro 4 update and build fix

### PR DESCRIPTION
**Pull request by revgum**
The update to Astro 4 and the `npm run build` seems to work without issue in this update. 

I see that the `npm run test` is broken on the main branch and remains broken on this PR. The `test/helpers.ts` has a hardcoded reference to astro.js which doesn't exist. I imagine this was part of some CI configuration that the previous team had setup and just hasn't been translated over to this repo.

### CODE REVIEW

**Comment by revgum** [comment]
I did use `yalc` to publish and link to a local build of this package for testing, and it looks like Astro 4 was running. 

Screenshot 2024-01-20 at 5 34 38 AM

**Comment by Ayfri** [comment]
In my opinion you should publish this as a separate package, I think they will never update this package again.

**Review by kt3k — APPROVED** [review]
LGTM

**Review by hashrock — APPROVED** [review]
LGTM

**Comment by Ayfri** [comment]
Oh finally, thanks !

**Comment by kt3k** [comment]
Hi @matthewp 

We'd like to publish this change to `@astrojs/deno` to make it up-to-date with Astro 4. Can we (Deno team) have publish access to that npm package? Or should we publish it as a different package?

**Comment by matthewp** [comment]
Hey @kt3k, sorry I missed the comment! We'd like to keep the `@astrojs` org to Astro core maintained packages, so I would recommend creating a new package for you to publish to.

**Comment by kt3k** [comment]
Thanks for your reply @matthewp! Ok. Got it. We'll publish it under a different name.

**Pull request merged**
